DE_PARA_GRUPOS = {
    'CURSOS E TREINAMENTOS': 'TREINAMENTOS',
    'MATERIAL DE LIMPEZA E HIGIENE': 'MATERIAL DE HIGIENE E LIMPEZA',
    'COMBUSTIVEIS E LUBRIFICANTES':'COMBUSTIVEIS DE VEICULOS',
    'CONTRIBUICAO SINDICAL PATRONAL':'CONTRIBUICAO SINDICAL',
    'FGTS RESCISORIO':'MULTA FGTS RESCISAO',
    'IPVA':'IPVA VEICULOS PROPRIOS',
    'RESCISAO':'PROVISAO DE RESCISAO',
    'ALIMENTACAO':'LANCHES E REFEICOES',
    'FGTS':'FGTS S/ FOLHA, ADICIONAIS E HE',
    'ICMS':'OUTROS IMPOSTOS E TAXAS',
    'LOCACAO DE MAQUI E EQUIPAMENTOS':'LOCACAO DE EQUIPAMENTOS',

    'LOCACAO DE MAQUINAS E EQUIPAMENTOS':'LOCACAO DE EQUIPAMENTOS',
    'OUTROS':'PROVISAO DE RISCO',
    'PASSAGENS':'PASSAGENS DE OBRA',
    'REEMBOLSO DESPESAS DE TERCEIROS':'PROVISAO DE RISCO',
    'SEGURO DE VIDA':'SEGURO DE VIDA EM GRUPO',
    'BRINDES E DOACOES':'BRINDES',
    'PIS':'OUTROS IMPOSTOS E TAXAS',
    'SERVICOS DE ADVOCACIA':'SERVICOS ADVOCATICIOS',
    'SERVICOS DE MANUTECAO':'SERVICOS DE MANUTECOES',
    'CALIBRACOES DE BENS' :'CALIBRACOES DE INSTRUMENTOS'




}